# Generated by Django 5.1.1 on 2025-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friendship_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
